export const allData = [
  {
    firstname: "Tony",
    lastname: "Stark",
    startdate: "03/01/2024",
    department: "Engineering",
    birthdate: "07/04/1970",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Steve",
    lastname: "Rogers",
    startdate: "03/01/2024",
    department: "Sales",
    birthdate: "07/04/1918",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Natasha",
    lastname: "Romanoff",
    startdate: "03/01/2024",
    department: "Marketing",
    birthdate: "11/22/1984",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Clint",
    lastname: "Barton",
    startdate: "03/01/2024",
    department: "Human Resources",
    birthdate: "01/07/1971",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Thor",
    lastname: "Odinson",
    startdate: "03/01/2024",
    department: "Legal",
    birthdate: "08/11/964",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Bruce",
    lastname: "Banner",
    startdate: "03/01/2024",
    department: "Engineering",
    birthdate: "12/18/1969",
    street: "Avengers' Tower",
    city: "New York",
    countryState: "NY",
    zipcode: "10000",
  },
  {
    firstname: "Peter",
    lastname: "Parker",
    startdate: "03/01/2024",
    department: "Engineering",
    birthdate: "08/10/2001",
    street: "23 Elm Street",
    city: "Queens",
    countryState: "NY",
    zipcode: "11377",
  },
  {
    firstname: "Carol",
    lastname: "Danvers",
    startdate: "03/01/2024",
    department: "Sales",
    birthdate: "03/17/1968",
    street: "789 Air Force Drive",
    city: "Washington D.C.",
    countryState: "DC",
    zipcode: "20001",
  },
  {
    firstname: "Scott",
    lastname: "Lang",
    startdate: "03/01/2024",
    department: "Engineering",
    birthdate: "06/11/1979",
    street: "543 Ant Avenue",
    city: "San Francisco",
    countryState: "CA",
    zipcode: "94102",
  },
  {
    firstname: "Wanda",
    lastname: "Maximoff",
    startdate: "03/01/2024",
    department: "Marketing",
    birthdate: "05/10/1989",
    street: "112 Sokovia Street",
    city: "Sokovia",
    countryState: "SK",
    zipcode: "12345",
  },
  {
    firstname: "Stephen",
    lastname: "Strange",
    startdate: "03/01/2024",
    department: "Legal",
    birthdate: "11/04/1963",
    street: "177A Bleecker Street",
    city: "New York",
    countryState: "NY",
    zipcode: "10012",
  },
  {
    firstname: "Sam",
    lastname: "Wilson",
    startdate: "03/01/2024",
    department: "Human Resources",
    birthdate: "11/23/1978",
    street: "567 Falcon Drive",
    city: "Harlem",
    countryState: "NY",
    zipcode: "10026",
  },
  {
    firstname: "T'Challa",
    lastname: "Wakanda",
    startdate: "03/01/2024",
    department: "Sales",
    birthdate: "02/16/1976",
    street: "1 Wakanda Way",
    city: "Wakanda",
    countryState: "WA",
    zipcode: "54321",
  },
  {
    firstname: "Pietro",
    lastname: "Maximoff",
    startdate: "03/01/2024",
    department: "Engineering",
    birthdate: "06/22/1989",
    street: "212 Sokovia Street",
    city: "Sokovia",
    countryState: "SK",
    zipcode: "12345",
  },
  {
    firstname: "James",
    lastname: "Rhodes",
    startdate: "03/01/2024",
    department: "Legal",
    birthdate: "11/22/1972",
    street: "456 Iron Patriot Lane",
    city: "Washington D.C.",
    countryState: "DC",
    zipcode: "20001",
  },
  {
    firstname: "Vision",
    lastname: "",
    startdate: "03/01/2024",
    department: "Marketing",
    birthdate: "05/05/2015",
    street: "789 Synthezoid Drive",
    city: "Unknown",
    countryState: "",
    zipcode: "",
  },
  {
    firstname: "Gamora",
    lastname: "",
    startdate: "03/01/2024",
    department: "Sales",
    birthdate: "03/15/1982",
    street: "123 Zen Whistler Lane",
    city: "Zen-Whoberi",
    countryState: "ZW",
    zipcode: "67890",
  },
  {
    firstname: "Nebula",
    lastname: "",
    startdate: "03/01/2024",
    department: "",
    birthdate: "",
    street: "",
    city: "",
    countryState: "",
    zipcode: "",
  },
  {
    firstname: "Bruce",
    lastname: "Wayne",
    startdate: "03/01/2024",
    department: "Legal",
    birthdate: "02/19/1972",
    street: "1007 Mountain Drive",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Clark",
    lastname: "Kent",
    startdate: "03/01/2024",
    department: "Journalism",
    birthdate: "06/18/1979",
    street: "1938 Sullivan Lane",
    city: "Metropolis",
    countryState: "NY",
    zipcode: "10036",
  },
  {
    firstname: "Diana",
    lastname: "Prince",
    startdate: "03/01/2024",
    department: "Diplomacy",
    birthdate: "09/21/1994",
    street: "Themyscira Isle",
    city: "Themyscira",
    countryState: "",
    zipcode: "",
  },
  {
    firstname: "Barry",
    lastname: "Allen",
    startdate: "03/01/2024",
    department: "Forensics",
    birthdate: "03/14/1989",
    street: "5252 52nd Street",
    city: "Central City",
    countryState: "MO",
    zipcode: "64112",
  },
  {
    firstname: "Arthur",
    lastname: "Curry",
    startdate: "03/01/2024",
    department: "Aquatic Sciences",
    birthdate: "01/29/1986",
    street: "Atlantic Ocean",
    city: "Atlantis",
    countryState: "",
    zipcode: "",
  },
  {
    firstname: "Victor",
    lastname: "Stone",
    startdate: "03/01/2024",
    department: "Technology",
    birthdate: "08/19/1992",
    street: "1313 Slaughter Swamp",
    city: "Central City",
    countryState: "MO",
    zipcode: "64112",
  },
  {
    firstname: "Oliver",
    lastname: "Queen",
    startdate: "03/01/2024",
    department: "Public Relations",
    birthdate: "05/16/1985",
    street: "252 Queen Industries Avenue",
    city: "Star City",
    countryState: "CA",
    zipcode: "90001",
  },
  {
    firstname: "Kara",
    lastname: "Zor-El",
    startdate: "03/01/2024",
    department: "Space Exploration",
    birthdate: "06/18/1990",
    street: "Argo City",
    city: "Krypton",
    countryState: "",
    zipcode: "",
  },
  {
    firstname: "Harleen",
    lastname: "Quinzel",
    startdate: "03/01/2024",
    department: "Psychiatry",
    birthdate: "04/20/1992",
    street: "12 Arkham Asylum Lane",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Pamela",
    lastname: "Isley",
    startdate: "03/01/2024",
    department: "Botany",
    birthdate: "11/12/1988",
    street: "14 Slaughter Swamp",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Edward",
    lastname: "Nygma",
    startdate: "03/01/2024",
    department: "Cryptography",
    birthdate: "08/02/1980",
    street: "Riddle House",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Selina",
    lastname: "Kyle",
    startdate: "03/01/2024",
    department: "Thievery",
    birthdate: "01/05/1986",
    street: "123 Cat Alley",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Bruce",
    lastname: "Banner",
    startdate: "03/01/2024",
    department: "Science",
    birthdate: "12/18/1969",
    street: "1313 Mockingbird Lane",
    city: "Gotham City",
    countryState: "NJ",
    zipcode: "07016",
  },
  {
    firstname: "Hal",
    lastname: "Jordan",
    startdate: "03/01/2024",
    department: "Aerospace",
    birthdate: "08/20/1981",
    street: "2814 North Fairbanks",
    city: "Coast City",
    countryState: "CA",
    zipcode: "90001",
  },
  {
    firstname: "John",
    lastname: "Jones",
    startdate: "03/01/2024",
    department: "Law Enforcement",
    birthdate: "11/17/1968",
    street: "478 Mars Avenue",
    city: "Mars",
    countryState: "",
    zipcode: "",
  },
];
